# alarm.yaml

- platform: template
  name: !secret alarm_name
  id: alarme_maison
  codes:
    - !secret alarm_code
  arming_away_time: 5s
  arming_night_time: 5s
  on_armed_away:
    then:
      - logger.log: "Alarme armée en mode away"
  on_armed_night:
    then:
      - logger.log: "Alarme armée en mode night"
  on_arming:
    then:
      - script.execute: check_opened
  on_triggered:
    then:
      - switch.turn_off: siren_alarme
      - script.execute:
          id: send_notification_push
          titre: "🚨 Alarme TRIGGERED"
          msg: "Un capteur a déclenché l'alarme dans la maison !"
  on_disarmed:
    then:
      - switch.turn_on: siren_alarme
