# main.yaml (main file)
esphome:
  name: alarm-esp32-eth
  on_boot:
    priority: -100
    then:
      - script.execute: turn_on_screen
      - delay: 1s
      - script.execute:
          id: update_lcd_display
          title: "Desactivee"

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

logger:
api:

i2c:
  sda: GPIO14
  scl: GPIO04
  scan: true

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20

output: !include outputs.yaml
switch: !include switches.yaml
alarm_control_panel: !include alarm.yaml
script: !include_dir_merge_list scripts/
binary_sensor: !include_dir_merge_list binary_sensors/
display: !include display.yaml