# binary_sensors/pir.yaml

- platform: gpio
  id: room_pir
  name: "Detecteur de mouvement chambre"
  device_class: motion
  pin:
    mcp23xxx: mcp23017_hub
    number: 1
    mode:
      input: true
      pullup: true

