# binary_sensors/pir.yaml

- platform: gpio
  name: "PIR chambre"
  device_class: motion
  pin:
    mcp23xxx: mcp23017_hub
    number: 1
    mode:
      input: true
      pullup: true
  on_press:
    then:
      - script.execute: check_trigger_alarme_away_30s
