# binary_sensors/windows.yaml

- platform: gpio
  name: "Fenetre chambre"
  id: room_window
  device_class: door
  pin:
    mcp23xxx: mcp23017_hub
    number: 0
    mode:
      input: true
      pullup: true